version: 0.1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t medtrack-backend:$IMAGE_TAG .
      - docker tag medtrack-backend:$IMAGE_TAG $ECR_REPO:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $ECR_REPO:latest
      - echo Updating Elastic Beanstalk...
      - aws elasticbeanstalk update-environment \
          --application-name medtrack-app \
          --environment-name medtrack-prod \
          --version-label $IMAGE_TAG
