services:
  - type: web
    name: medtrack-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: your-super-secure-secret-key-at-least-256-bits-long
      - key: DATABASE_URL
        value: your-postgresql-connection-string-here
      - key: CORS_ORIGIN
        value: https://medtrack-frontend.onrender.com

  - type: web
    name: medtrack-frontend
    runtime: static
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://medtrack-backend.onrender.com/api
