services:
  - type: web
    name: medtrack-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production

  - type: static
    name: medtrack-frontend
    buildCommand: cd frontend && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://medtrack-backend.onrender.com/api
