services:
  - type: web
    name: medtrack-backend
    runtime: node
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npx prisma migrate deploy
    startCommand: cd backend && node simple-server.js
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://medtrack_user:NJtHALKRvCK1sqADVNfEE3W5iKqpPpNR@dpg-d40bg595pdvs73frbc3g-a.singapore-postgres.render.com/medtrack_db_uu6m

  - type: web
    name: medtrack-frontend
    runtime: static
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://medtrack-backend.onrender.com/api